languageCode = "ja"
title = "kazkn.com"
baseurl = "https://kazkn.com/"
hasCJKLanguage = true
theme = "myblank"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[params]
author = "Kazuki Nishikawa"
