name: deploy

on:
  push:
    branches: [ hugo ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: hugo

    - name: Commit
      run: |
        git config --local user.email "kz.nishikawa@gmail.com"
        git config --local user.name "Kazuki Nishikawa"
        git commit -am "actions build"
      working-directory: public

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      working-directory: public
